# Generated by Django 3.2.8 on 2023-02-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='point',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
