# Generated by Django 3.2.8 on 2023-03-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_achievement_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='vote',
            field=models.BooleanField(default=False),
        ),
    ]
